backend:
  name: git-gateway
  branch: main

media_folder: "src/_uploads"
public_folder: "/_uploads"

collections:
  - name: "carousel"
    label: "Carousel"
    folder: "src/_data/carousel"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      # Add more fields as needed

  - name: "navigation"
    label: "Navigation"
    files:
      - file: "src/_data/navigation.yaml"
        label: "Navigation"
        name: "navigation"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          # Add more fields as needed

  # Add more collections for other content types like text content
